import { useEffect, useState } from 'react';
import { Alert, Badge, Button, Form, ListGroup } from 'react-bootstrap';
import { Link, useNavigate, useParams } from 'react-router';
import { ComposeUrl, Delete, endpoints, get, post } from '@morwalpizvideo/services';
import type { RbacGroup, RbacUserSummary } from './types';

export default function RbacGroupDetailPage() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const [group, setGroup] = useState<RbacGroup | null>(null); const [users, setUsers] = useState<RbacUserSummary[]>([]); const [search, setSearch] = useState(''); const [error, setError] = useState(false); const endpoint = ComposeUrl(endpoints.RBAC_GROUPS_DETAIL, { id: encodeURIComponent(id) });
  useEffect(() => { void Promise.all([get(endpoint), get(endpoints.RBAC_USERS)]).then(([loadedGroup, loadedUsers]) => { setGroup(loadedGroup as RbacGroup); setUsers((loadedUsers as RbacUserSummary[]) ?? []); }).catch(() => setError(true)); }, [endpoint]);
  const members = group?.members ?? [];
  const memberIds = new Set(members.map(member => member.id));
  const candidates = users.filter(user => !memberIds.has(user.id) && `${user.username} ${user.email}`.toLowerCase().includes(search.toLowerCase()));
  async function updateMembership(userId: string, add: boolean) { try { const membershipEndpoint = ComposeUrl(endpoints.RBAC_USER_GROUP, { id: userId, groupId: id }); if (add) await post(membershipEndpoint, {}); else await Delete(membershipEndpoint); setGroup(await get(endpoint) as RbacGroup); } catch { setError(true); } }
  async function remove() { if (!window.confirm('Delete this group? Members will lose this membership.')) return; try { await Delete(endpoint); navigate('/rbac/groups'); } catch { setError(true); } }
  if (!group && !error) return <p>Loading group...</p>;
  return <div className="rbac-form-width">{error ? <Alert variant="danger">Unable to load group.</Alert> : null}{group ? <><div className="d-flex justify-content-between align-items-center gap-3 mb-3"><h1 className="h3 mb-0">{group.name}</h1><Link className="btn btn-outline-primary" to={`/rbac/groups/${id}/edit`}>Edit</Link></div><dl className="row"><dt className="col-sm-4">Code</dt><dd className="col-sm-8">{group.code}</dd><dt className="col-sm-4">Status</dt><dd className="col-sm-8">{group.isActive ? 'Active' : 'Inactive'}</dd><dt className="col-sm-4">Members</dt><dd className="col-sm-8">{group.memberCount}</dd><dt className="col-sm-4">Description</dt><dd className="col-sm-8">{group.description || 'None'}</dd><dt className="col-sm-4">Permissions</dt><dd className="col-sm-8">{group.permissions.map(permission => <Badge key={permission} bg="secondary" className="me-1 mb-1">{permission}</Badge>)}</dd></dl><section><h2 className="h5">Group members</h2><ListGroup className="mb-3">{members.map(member => <ListGroup.Item key={member.id} className="d-flex justify-content-between"><span>{member.username} <small className="text-muted">{member.email}</small></span><Button size="sm" variant="outline-danger" onClick={() => void updateMembership(member.id, false)}>Remove</Button></ListGroup.Item>)}</ListGroup><Form.Control aria-label="Search users" placeholder="Search users" value={search} onChange={event => setSearch(event.target.value)} />{candidates.slice(0, 10).map(user => <Button key={user.id} className="me-2 mt-2" size="sm" variant="outline-primary" onClick={() => void updateMembership(user.id, true)}>Add {user.username}</Button>)}</section><Button className="mt-3" variant="outline-danger" onClick={() => void remove()}>Delete group</Button></> : null}</div>;
}