import { useState } from 'react';
import type { ReactNode } from 'react';
import { Link, useNavigate } from 'react-router';
import { availability, book, login, register, type Availability, type Account } from './api';

function Shell({ account, children }: { account: Account | null; children: ReactNode }) { return <main><header><div><span className="eyebrow">PEPPERBOX</span><h1>Campo da tiro</h1></div><nav><Link to="/">Prenota</Link><Link to="/messages">Messaggi</Link>{account?.isAdmin && <Link to="/admin">Admin</Link>}</nav></header>{children}</main>; }
export function Auth({ onLogin }: { onLogin: (account: Account) => void }) { const [mode, setMode] = useState<'login' | 'register'>('login'); const [form, setForm] = useState({ username: '', password: '', firstName: '', lastName: '' }); const [error, setError] = useState(''); const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { const result = mode === 'login' ? await login(form) : await register(form); if (mode === 'login') onLogin(result); else setMode('login'); } catch (error) { setError(error instanceof Error ? error.message : 'Operazione non riuscita'); } }; return <section className="auth"><span className="eyebrow">ACCESSO</span><h2>{mode === 'login' ? 'Bentornato' : 'Richiedi un account'}</h2><p className="muted">Gli account nuovi restano in attesa dell'approvazione dell'amministratore.</p><form onSubmit={submit}>{mode === 'register' && <><input required placeholder="Nome" onChange={e => setForm({ ...form, firstName: e.target.value })} /><input required placeholder="Cognome" onChange={e => setForm({ ...form, lastName: e.target.value })} /></>}<input required placeholder="Username" onChange={e => setForm({ ...form, username: e.target.value })} /><input required minLength={12} type="password" placeholder="Password" onChange={e => setForm({ ...form, password: e.target.value })} /><button>{mode === 'login' ? 'Accedi' : 'Invia richiesta'}</button></form>{error && <p className="error">{error}</p>}<button className="link-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Non hai un account?' : 'Hai già un account?'}</button></section>; }
export function Booking({ account }: { account: Account }) { const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [period, setPeriod] = useState('morning'); const [data, setData] = useState<Availability | null>(null); const [error, setError] = useState(''); const search = async () => { try { setError(''); setData(await availability(date, period)); } catch (e) { setError(e instanceof Error ? e.message : 'Errore'); } }; const reserve = async (bayId: string) => { try { await book({ bayId, localDate: date, periodKey: period, request: '' }); await search(); } catch (e) { setError(e instanceof Error ? e.message : 'Conflitto: scegli un altro slot'); } }; return <Shell account={account}><section className="hero"><span className="eyebrow">PRENOTAZIONI</span><h2>Trova il tuo prossimo turno.</h2><p>Disponibilità calcolata nel fuso del campo. Le richieste pending bloccano lo slot.</p></section><section className="toolbar"><label>Data<input type="date" value={date} onChange={e => setDate(e.target.value)} /></label><label>Sessione<select value={period} onChange={e => setPeriod(e.target.value)}><option value="morning">Mattina</option><option value="afternoon">Pomeriggio</option></select></label><button onClick={search}>Cerca disponibilità</button></section>{error && <p className="error">{error}</p>}{data && <section><div className="section-heading"><h3>{data.bays.length} bay disponibili</h3><span>{new Date(data.startUtc).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div><div className="grid">{data.bays.map(bay => <article className="bay" key={bay.id}><span className="bay-code">{bay.code}</span><h3>{bay.description || 'Postazione operativa'}</h3><p>{bay.mechanisms.map(item => `${item.quantity} ${item.type}`).join(' · ') || 'Configurazione standard'}</p><button onClick={() => reserve(bay.id)}>Richiedi bay</button></article>)}</div></section>}<p className="muted account-note">Account: {account.firstName} {account.lastName} · {account.status}</p></Shell>; }
export function App() { const [account, setAccount] = useState<Account | null>(null); const navigate = useNavigate(); return account ? <Booking account={account} /> : <Shell account={null}><Auth onLogin={value => { setAccount(value); navigate('/'); }} /></Shell>; }
