import React, { useEffect, useState } from 'react';
import { Button, Form } from 'react-bootstrap';
import { useFetcher, useLoaderData } from 'react-router';
import { NavigationItemType } from '@morwalpizvideo/models';
import type { ChannelNavigation, NavigationMenuItem, PageAdmin, SaveNavigationDTO } from '@morwalpizvideo/models';
import { useToast } from '@components/ToastNotification/ToastContext';
import GenericErrorList from '@components/GenericErrorList';
import PageHeader from '@components/PageHeader';

const emptyItem = (column = 0): NavigationMenuItem => ({ type: NavigationItemType.Internal, pageId: undefined, targetUrl: '/', displayText: '', column, displayOrder: 0 });

function ItemEditor({ item, pages, onChange, onRemove }: { item: NavigationMenuItem; pages: PageAdmin[]; onChange: (item: NavigationMenuItem) => void; onRemove: () => void }): React.ReactElement {
  return <div className="border rounded p-2 mb-2"><div className="row g-2"><Form.Group className="col-md-2"><Form.Label>Type</Form.Label><Form.Select value={item.type} onChange={event => onChange({ ...item, type: Number(event.target.value) as NavigationMenuItem['type'] })}><option value={NavigationItemType.Page}>Page</option><option value={NavigationItemType.Internal}>Internal</option><option value={NavigationItemType.External}>External</option></Form.Select></Form.Group><Form.Group className="col-md-3"><Form.Label>Label</Form.Label><Form.Control value={item.displayText} onChange={event => onChange({ ...item, displayText: event.target.value })} /></Form.Group><Form.Group className="col-md-5"><Form.Label>{item.type === NavigationItemType.Page ? 'Page' : 'Target URL'}</Form.Label>{item.type === NavigationItemType.Page ? <Form.Select value={item.pageId ?? ''} onChange={event => onChange({ ...item, pageId: event.target.value, targetUrl: '' })}><option value="">Choose a page</option>{pages.filter(page => page.status === 1).map(page => <option key={page.id} value={page.id}>{page.title} ({page.url})</option>)}</Form.Select> : <Form.Control value={item.targetUrl} onChange={event => onChange({ ...item, targetUrl: event.target.value })} placeholder={item.type === NavigationItemType.Internal ? '/path' : 'https://example.com'} />}</Form.Group><Form.Group className="col-md-1"><Form.Label>Order</Form.Label><Form.Control type="number" min="0" value={item.displayOrder} onChange={event => onChange({ ...item, displayOrder: Number(event.target.value) || 0 })} /></Form.Group><div className="col-md-1 d-flex align-items-end"><Button variant="outline-danger" onClick={onRemove}>Remove</Button></div></div></div>;
}

export default function NavigationPage(): React.ReactElement {
  const data = useLoaderData() as { navigation: ChannelNavigation | null; pages: PageAdmin[] };
  const fetcher = useFetcher();
  const toast = useToast();
  const [active, setActive] = useState(data.navigation?.isActive ?? true);
  const [columns, setColumns] = useState(data.navigation?.footerColumnCount ?? 1);
  const [header, setHeader] = useState<NavigationMenuItem[]>(data.navigation?.headerItems ?? []);
  const [footer, setFooter] = useState<NavigationMenuItem[]>(data.navigation?.footerItems ?? []);
  useEffect(() => { if (fetcher.state === 'idle' && fetcher.data?.success) toast.show('Success', 'Navigation saved successfully', { variant: 'success' }); }, [fetcher.data, fetcher.state, toast]);
  const submit = () => { const payload: SaveNavigationDTO = { isActive: active, footerColumnCount: columns, headerItems: header.map((item, index) => ({ ...item, displayOrder: index, column: 0 })), footerItems: footer.map((item, index) => ({ ...item, displayOrder: index, column: Math.min(item.column, columns - 1) })) }; fetcher.submit({ navigation: JSON.stringify(payload) }, { method: 'put' }); };
  const add = (target: 'header' | 'footer') => target === 'header' ? setHeader(items => [...items, { ...emptyItem(), displayOrder: items.length }]) : setFooter(items => [...items, { ...emptyItem(Math.max(0, columns - 1)), displayOrder: items.length }]);
  return <><PageHeader title="Navigation" /><GenericErrorList errors={fetcher.data?.errors} /><Form.Check className="mb-3" type="switch" label="Active public navigation" checked={active} onChange={event => setActive(event.target.checked)} /><Form.Group className="mb-4"><Form.Label>Footer columns</Form.Label><Form.Control type="number" min="1" max="8" value={columns} onChange={event => setColumns(Math.max(1, Math.min(8, Number(event.target.value) || 1)))} /></Form.Group><h5>Header</h5>{header.map((item, index) => <ItemEditor key={`header-${index}`} item={item} pages={data.pages} onChange={next => setHeader(items => items.map((current, itemIndex) => itemIndex === index ? next : current))} onRemove={() => setHeader(items => items.filter((_, itemIndex) => itemIndex !== index))} />)}<Button variant="outline-secondary" onClick={() => add('header')}>Add header item</Button><h5 className="mt-4">Footer</h5>{footer.map((item, index) => <div key={`footer-${index}`}><ItemEditor item={item} pages={data.pages} onChange={next => setFooter(items => items.map((current, itemIndex) => itemIndex === index ? next : current))} onRemove={() => setFooter(items => items.filter((_, itemIndex) => itemIndex !== index))} /><Form.Select className="mb-2" value={item.column} onChange={event => setFooter(items => items.map((current, itemIndex) => itemIndex === index ? { ...current, column: Number(event.target.value) } : current))}>{Array.from({ length: columns }, (_, column) => <option key={column} value={column}>Footer column {column + 1}</option>)}</Form.Select></div>)}<Button variant="outline-secondary" onClick={() => add('footer')}>Add footer item</Button><div className="mt-4"><Button disabled={fetcher.state !== 'idle'} onClick={submit}>Save navigation</Button></div></>;
}