// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MorWalPiz.VideoImporter.Data;

#nullable disable

namespace MorWalPiz.VideoImporter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250616193759_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("MorWalPiz.VideoImporter.Models.Disclaimer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Disclaimers");
                });

            modelBuilder.Entity("MorWalPiz.VideoImporter.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "it",
                            IsDefault = true,
                            IsSelected = true,
                            Name = "Italiano"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            IsDefault = false,
                            IsSelected = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Code = "fr",
                            IsDefault = false,
                            IsSelected = false,
                            Name = "Français"
                        },
                        new
                        {
                            Id = 4,
                            Code = "de",
                            IsDefault = false,
                            IsSelected = false,
                            Name = "Deutsch"
                        },
                        new
                        {
                            Id = 5,
                            Code = "es",
                            IsDefault = false,
                            IsSelected = true,
                            Name = "Español"
                        });
                });

            modelBuilder.Entity("MorWalPiz.VideoImporter.Models.PublishSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PublishTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PublishSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DaysOfWeek = 31,
                            IsActive = true,
                            Name = "Giorni feriali",
                            PublishTime = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DaysOfWeek = 96,
                            IsActive = true,
                            Name = "Weekend",
                            PublishTime = new TimeSpan(0, 13, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("MorWalPiz.VideoImporter.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultHashtags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiEndpoint = "https://localhost:7221",
                            DefaultHashtags = "#video #hashtag"
                        });
                });

            modelBuilder.Entity("MorWalPiz.VideoImporter.Models.Disclaimer", b =>
                {
                    b.HasOne("MorWalPiz.VideoImporter.Models.Language", "Language")
                        .WithMany("Disclaimers")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("MorWalPiz.VideoImporter.Models.Language", b =>
                {
                    b.Navigation("Disclaimers");
                });
#pragma warning restore 612, 618
        }
    }
}
